const DEFAULT_COMPANY = "teleGlobals International Pvt. Ltd.";
const DEFAULT_ADDRESS =
  "Cerebrum IT Park, B-3, Office No.4B, Kalyani Nagar, Pune, Maharashtra - 411014";

const companyProfile = {
  name: DEFAULT_COMPANY,
  logo: "",
  about:
    "teleGlobals International Pvt. Ltd. connects global business horizons with technology, talent, and trusted delivery.",
  website: "https://teleglobals.com",
  corporateOfficeAddress: DEFAULT_ADDRESS,
  otherLocations: ["Mumbai Delivery Center", "Bengaluru Innovation Hub"],
  contactNumber: "+91 20 0000 0000",
  contactEmail: "info@teleglobals.com",
  ceoName: "Rahul Sharma",
  founderName: "Meera Joshi",
  badgesAndCertificates: ["ISO 27001", "Great Place to Work", "NASSCOM Member"],
  mission:
    "Deliver reliable digital identity and workplace solutions that keep people and organizations connected.",
  vision: "To be the trusted partner for global businesses building secure, modern workplaces.",
  companyDeckUrl: "",
};

const adminUser = {
  employeeId: "ADMIN001",
  name: "System Admin",
  email: "admin@teleglobals.com",
  phone: "+91 9000000000",
  password: "admin123",
  company: DEFAULT_COMPANY,
  designation: "Administrator",
  department: "IT",
  reportingHead: "Board",
  officeAddress: DEFAULT_ADDRESS,
  bloodGroup: "O+ve",
  dateOfBirth: "15/03/1988",
  dateOfJoining: "01/01/2020",
  emergencyNo: "+91 9000000000",
  linkedin: "https://linkedin.com/in/teleglobals-admin",
  instagram: "",
  facebook: "",
  photo: "",
  role: "ADMIN",
  approvalStatus: "APPROVED",
  status: "ACTIVE",
};

const employees = [
  {
    employeeId: "TIPL100785",
    name: "Ayush Kawane",
    email: "ayush@teleglobals.com",
    phone: "+91 9876543210",
    company: DEFAULT_COMPANY,
    designation: "Software Engineer",
    department: "Engineering",
    reportingHead: "Rahul Sharma",
    officeAddress: DEFAULT_ADDRESS,
    bloodGroup: "B+ve",
    dateOfBirth: "12/08/1998",
    dateOfJoining: "28/07/2026",
    emergencyNo: "+91 9011922733",
    linkedin: "https://linkedin.com/in/ayush-kawane",
    instagram: "",
    facebook: "",
    photo: "",
    status: "ACTIVE",
  },
  {
    employeeId: "TIPL100786",
    name: "Priya Deshmukh",
    email: "priya.deshmukh@teleglobals.com",
    phone: "+91 9822011122",
    company: DEFAULT_COMPANY,
    designation: "HR Manager",
    department: "Human Resources",
    reportingHead: "Meera Joshi",
    officeAddress: DEFAULT_ADDRESS,
    bloodGroup: "A+ve",
    dateOfBirth: "04/11/1992",
    dateOfJoining: "12/03/2024",
    emergencyNo: "+91 9822011199",
    linkedin: "https://linkedin.com/in/priya-deshmukh",
    instagram: "priya.deshmukh",
    facebook: "",
    photo: "",
    status: "ACTIVE",
  },
  {
    employeeId: "TIPL100787",
    name: "Rohan Mehta",
    email: "rohan.mehta@teleglobals.com",
    phone: "+91 9765432109",
    company: DEFAULT_COMPANY,
    designation: "Product Designer",
    department: "Design",
    reportingHead: "Ananya Iyer",
    officeAddress: DEFAULT_ADDRESS,
    bloodGroup: "O+ve",
    dateOfBirth: "22/06/1995",
    dateOfJoining: "05/09/2023",
    emergencyNo: "+91 9765432110",
    linkedin: "https://linkedin.com/in/rohan-mehta",
    instagram: "",
    facebook: "rohan.mehta",
    photo: "",
    status: "ACTIVE",
  },
  {
    employeeId: "TIPL100788",
    name: "Sneha Patil",
    email: "sneha.patil@teleglobals.com",
    phone: "+91 9900112233",
    company: DEFAULT_COMPANY,
    designation: "Accountant",
    department: "Finance",
    reportingHead: "Karan Malhotra",
    officeAddress: DEFAULT_ADDRESS,
    bloodGroup: "AB+ve",
    dateOfBirth: "09/01/1994",
    dateOfJoining: "18/11/2022",
    emergencyNo: "+91 9900112244",
    linkedin: "https://linkedin.com/in/sneha-patil",
    instagram: "",
    facebook: "",
    photo: "",
    status: "INACTIVE",
  },
  {
    employeeId: "TIPL100789",
    name: "Vikram Singh",
    email: "vikram.singh@teleglobals.com",
    phone: "+91 9811122233",
    company: DEFAULT_COMPANY,
    designation: "DevOps Engineer",
    department: "Infrastructure",
    reportingHead: "Rahul Sharma",
    officeAddress: DEFAULT_ADDRESS,
    bloodGroup: "B-ve",
    dateOfBirth: "30/09/1991",
    dateOfJoining: "22/01/2025",
    emergencyNo: "+91 9811122244",
    linkedin: "https://linkedin.com/in/vikram-singh",
    instagram: "vikram.singh",
    facebook: "",
    photo: "",
    status: "ACTIVE",
  },
];

module.exports = { employees, adminUser, companyProfile, DEFAULT_COMPANY, DEFAULT_ADDRESS };
